[project]
name = "andalucia-datahub-v2-0"
version = "0.1.0"
description = ""
authors = [
    {name = "Ricardo Fernández Chamorro",email = "databaandsc@gmail.com"}
]
requires-python = ">=3.14"
dependencies = [
    "requests (>=2.34.2,<3.0.0)",
    "polars (>=1.43.2,<2.0.0)",
    "sqlalchemy (>=2.0.52,<3.0.0)",
    "psycopg2-binary (>=2.9.12,<3.0.0)",
    "python-dotenv (>=1.2.3,<2.0.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.53.0,<0.54.0)"
]

[tool.poetry]
packages = [{include = "andalucia_datahub_v2"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
